name: Workflow Wayshub-backend

on:
  push:
    branches: ["master"]

  pull_request:
    branches: ["master"]

jobs:

  build:
    runs-on: ubuntu-22.04
    environment: development

    steps:
      - name: Checkout SCM
        uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build \
            -t daffaalmaas74/wayshub-backend:development .

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push image
        run: |
          docker push daffaalmaas74/wayshub-backend:development


  testing:
    needs: build
    runs-on: ubuntu-22.04
    environment: development

    steps:
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY_SERVER_BACKEND }}

      - name: Testing backend
        env:
          BACKEND_SERVER: ${{ secrets.SERVER_BACKEND }}

        run: |
          ssh -o StrictHostKeyChecking=no "$BACKEND_SERVER" << 'EOF'

          cd ~/wayshub-backend

          docker compose down

          docker rm -f backend-testing 2>/dev/null || true

          docker pull daffaalmaas74/wayshub-backend:development

          docker run -d \
            --name backend-testing \
            --network daffaalmaas \
            -p 5000:5000 \
            daffaalmaas74/wayshub-backend:development

          sleep 15

          if wget --spider --timeout=10 http://localhost:5000/health; then

              echo "Testing berhasil."

              docker stop backend-testing
              docker rm backend-testing

          else

              echo "Testing gagal."

              docker logs backend-testing

              docker stop backend-testing || true
              docker rm backend-testing || true

              echo "Menjalankan kembali backend production..."

              docker compose up -d

              exit 1

          fi

          EOF


  deploy:
    needs: testing
    runs-on: ubuntu-22.04
    environment: development

    steps:
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY_SERVER_BACKEND }}

      - name: Deploy backend
        env:
          BACKEND_SERVER: ${{ secrets.SERVER_BACKEND }}

        run: |
          ssh -o StrictHostKeyChecking=no "$BACKEND_SERVER" << 'EOF'

          cd ~/wayshub-backend

          docker compose pull

          docker compose down

          docker compose up -d

          EOF
