name: Workflow Wayshub-backend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: development

    steps:
      - name: Checkout SCM
        uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build -t daffaalmaas74/wayshub-backend:development .

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_token }}

      - name: Docker push
        run: |
          docker push daffaalmaas74/wayshub-backend:development
