name: Workflow Wayshub-backend

on:
push:
branches: ["master"]

pull_request:
branches: ["master"]

jobs:

build:
runs-on: ubuntu-22.04
environment: development

steps:

  - name: Setup SSH Agent
    uses: webfactory/ssh-agent@v0.9.1
    with:
      ssh-private-key: ${{ secrets.PRIVATE_KEY_SERVER_BACKEND }}

  - name: Build image
    env:
      BACKEND_SERVER: ${{ secrets.SERVER_BACKEND }}

    run: |
      ssh -o StrictHostKeyChecking=no "$BACKEND_SERVER" << 'EOF'

      cd ~/wayshub-backend

      docker compose down

      docker build \
        -t wayshub-backend:testing \
        .

      EOF


test:
needs: build
runs-on: ubuntu-22.04
environment: development

steps:

  - name: Setup SSH Agent
    uses: webfactory/ssh-agent@v0.9.1
    with:
      ssh-private-key: ${{ secrets.PRIVATE_KEY_SERVER_BACKEND }}

  - name: Test image
    env:
      BACKEND_SERVER: ${{ secrets.SERVER_BACKEND }}

    run: |
      ssh -o StrictHostKeyChecking=no "$BACKEND_SERVER" << 'EOF'

      cd ~/wayshub-backend

      docker rm -f backend-testing 2>/dev/null || true

      docker run -d \
        --name backend-testing \
        --network daffaalmaas \
        -p 5000:5000 \
        wayshub-backend:testing

      sleep 15

      HTTP_CODE=$(curl \
        --max-time 10 \
        -s \
        -o /dev/null \
        -w "%{http_code}" \
        http://localhost:5000)

      if [ "$HTTP_CODE" -ge 100 ] && [ "$HTTP_CODE" -lt 500 ]; then

          docker stop backend-testing
          docker rm backend-testing

      else

          docker logs backend-testing

          docker stop backend-testing || true
          docker rm backend-testing || true

          docker rmi wayshub-backend:testing || true

          docker compose up -d

          exit 1

      fi

      EOF


push:
needs: test
runs-on: ubuntu-22.04
environment: development

steps:

  - name: Setup SSH Agent
    uses: webfactory/ssh-agent@v0.9.1
    with:
      ssh-private-key: ${{ secrets.PRIVATE_KEY_SERVER_BACKEND }}

  - name: Push image
    env:
      BACKEND_SERVER: ${{ secrets.SERVER_BACKEND }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

    run: |
      ssh -o StrictHostKeyChecking=no "$BACKEND_SERVER" << EOF

      cd ~/wayshub-backend

      docker login \
        -u "${DOCKER_USERNAME}" \
        -p "${DOCKER_TOKEN}"

      docker tag \
        wayshub-backend:testing \
        daffaalmaas74/wayshub-backend:development

      docker push \
        daffaalmaas74/wayshub-backend:development

      EOF


deploy:
needs: push
runs-on: ubuntu-22.04
environment: development

steps:

  - name: Setup SSH Agent
    uses: webfactory/ssh-agent@v0.9.1
    with:
      ssh-private-key: ${{ secrets.PRIVATE_KEY_SERVER_BACKEND }}

  - name: Deploy
    env:
      BACKEND_SERVER: ${{ secrets.SERVER_BACKEND }}

    run: |
      ssh -o StrictHostKeyChecking=no "$BACKEND_SERVER" << 'EOF'

      cd ~/wayshub-backend

      docker compose pull

      docker compose down

      docker compose up -d

      EOF
